/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStatsIndexRouteImport } from './routes/_authenticated/stats/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProxiesIndexRouteImport } from './routes/_authenticated/proxies/index'
import { Route as AuthenticatedPlatformsIndexRouteImport } from './routes/_authenticated/platforms/index'
import { Route as AuthenticatedNovncIndexRouteImport } from './routes/_authenticated/novnc/index'
import { Route as AuthenticatedMailboxesIndexRouteImport } from './routes/_authenticated/mailboxes/index'
import { Route as AuthenticatedLifecycleIndexRouteImport } from './routes/_authenticated/lifecycle/index'
import { Route as AuthenticatedHealthIndexRouteImport } from './routes/_authenticated/health/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsIndexRoute = AuthenticatedStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProxiesIndexRoute =
  AuthenticatedProxiesIndexRouteImport.update({
    id: '/proxies/',
    path: '/proxies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformsIndexRoute =
  AuthenticatedPlatformsIndexRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovncIndexRoute = AuthenticatedNovncIndexRouteImport.update({
  id: '/novnc/',
  path: '/novnc/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailboxesIndexRoute =
  AuthenticatedMailboxesIndexRouteImport.update({
    id: '/mailboxes/',
    path: '/mailboxes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLifecycleIndexRoute =
  AuthenticatedLifecycleIndexRouteImport.update({
    id: '/lifecycle/',
    path: '/lifecycle/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthIndexRoute =
  AuthenticatedHealthIndexRouteImport.update({
    id: '/health/',
    path: '/health/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/health/': typeof AuthenticatedHealthIndexRoute
  '/lifecycle/': typeof AuthenticatedLifecycleIndexRoute
  '/mailboxes/': typeof AuthenticatedMailboxesIndexRoute
  '/novnc/': typeof AuthenticatedNovncIndexRoute
  '/platforms/': typeof AuthenticatedPlatformsIndexRoute
  '/proxies/': typeof AuthenticatedProxiesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stats/': typeof AuthenticatedStatsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/health': typeof AuthenticatedHealthIndexRoute
  '/lifecycle': typeof AuthenticatedLifecycleIndexRoute
  '/mailboxes': typeof AuthenticatedMailboxesIndexRoute
  '/novnc': typeof AuthenticatedNovncIndexRoute
  '/platforms': typeof AuthenticatedPlatformsIndexRoute
  '/proxies': typeof AuthenticatedProxiesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stats': typeof AuthenticatedStatsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/health/': typeof AuthenticatedHealthIndexRoute
  '/_authenticated/lifecycle/': typeof AuthenticatedLifecycleIndexRoute
  '/_authenticated/mailboxes/': typeof AuthenticatedMailboxesIndexRoute
  '/_authenticated/novnc/': typeof AuthenticatedNovncIndexRoute
  '/_authenticated/platforms/': typeof AuthenticatedPlatformsIndexRoute
  '/_authenticated/proxies/': typeof AuthenticatedProxiesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stats/': typeof AuthenticatedStatsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/accounts/'
    | '/dashboard/'
    | '/health/'
    | '/lifecycle/'
    | '/mailboxes/'
    | '/novnc/'
    | '/platforms/'
    | '/proxies/'
    | '/settings/'
    | '/stats/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/dashboard'
    | '/health'
    | '/lifecycle'
    | '/mailboxes'
    | '/novnc'
    | '/platforms'
    | '/proxies'
    | '/settings'
    | '/stats'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/accounts/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/health/'
    | '/_authenticated/lifecycle/'
    | '/_authenticated/mailboxes/'
    | '/_authenticated/novnc/'
    | '/_authenticated/platforms/'
    | '/_authenticated/proxies/'
    | '/_authenticated/settings/'
    | '/_authenticated/stats/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/': {
      id: '/_authenticated/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof AuthenticatedStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxies/': {
      id: '/_authenticated/proxies/'
      path: '/proxies'
      fullPath: '/proxies/'
      preLoaderRoute: typeof AuthenticatedProxiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms/': {
      id: '/_authenticated/platforms/'
      path: '/platforms'
      fullPath: '/platforms/'
      preLoaderRoute: typeof AuthenticatedPlatformsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novnc/': {
      id: '/_authenticated/novnc/'
      path: '/novnc'
      fullPath: '/novnc/'
      preLoaderRoute: typeof AuthenticatedNovncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mailboxes/': {
      id: '/_authenticated/mailboxes/'
      path: '/mailboxes'
      fullPath: '/mailboxes/'
      preLoaderRoute: typeof AuthenticatedMailboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lifecycle/': {
      id: '/_authenticated/lifecycle/'
      path: '/lifecycle'
      fullPath: '/lifecycle/'
      preLoaderRoute: typeof AuthenticatedLifecycleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health/': {
      id: '/_authenticated/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthenticatedHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedHealthIndexRoute: typeof AuthenticatedHealthIndexRoute
  AuthenticatedLifecycleIndexRoute: typeof AuthenticatedLifecycleIndexRoute
  AuthenticatedMailboxesIndexRoute: typeof AuthenticatedMailboxesIndexRoute
  AuthenticatedNovncIndexRoute: typeof AuthenticatedNovncIndexRoute
  AuthenticatedPlatformsIndexRoute: typeof AuthenticatedPlatformsIndexRoute
  AuthenticatedProxiesIndexRoute: typeof AuthenticatedProxiesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStatsIndexRoute: typeof AuthenticatedStatsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedHealthIndexRoute: AuthenticatedHealthIndexRoute,
  AuthenticatedLifecycleIndexRoute: AuthenticatedLifecycleIndexRoute,
  AuthenticatedMailboxesIndexRoute: AuthenticatedMailboxesIndexRoute,
  AuthenticatedNovncIndexRoute: AuthenticatedNovncIndexRoute,
  AuthenticatedPlatformsIndexRoute: AuthenticatedPlatformsIndexRoute,
  AuthenticatedProxiesIndexRoute: AuthenticatedProxiesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStatsIndexRoute: AuthenticatedStatsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
